# ========================================
# Note:  If you make changes to this CI/CD, please include someone from DevOps in the list of reviewers for the PR.
# ========================================
name: Build and Deploy
on: push
jobs:
  react-check-and-publish:
    name: React Check & Publish Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: pennlabs/shared-actions/.github/workflows/react.yaml@v0.1.2
        with:
          imageName: website
          githubRef: ${{ github.ref }}
          gitSha: ${{ github.sha }}
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: pennlabs/shared-actions/.github/workflows/deployment.yaml@v0.1.2
        with:
          githubRef: ${{ github.ref }}
          gitSha: ${{ github.sha }}
    needs:
      - react-check-and-publish
